#!/bin/bash

# generic docker run with our "mount" stuff, but command/args passed in as if
# you know what you're doing.
#
# for example ./dockerrun splitter ./2020TreeRecycling.xlsx
# or ./dockerrun bash splitter

if ! docker image inspect splitter >/dev/null && \
   ! docker image inspect printer >/dev/null
    then ./dockerbuild
fi

docker run --rm -it --mount type=bind,source="$(pwd)",target=/WorkDir --entrypoint "$@"
